### PR TITLE
Add chainide course

### PR DESCRIPTION
**Pull request by wufengtao1**
## 変更内容

Add .\docs\Polygon-Whitelist-NFT [ChainIDE]

## 背景

From Eggplanet@ChainIDE

## 備考

Just \docs\Polygon-Whitelist-NFT [ChainIDE]

Note: 

All relevant images and code resources are stored in the .\docs\Polygon-Whitelist-NFT [ChainIDE]\resource directory, not in the public\images directory. Additionally, the images are not named in the format of 0_1_2.png. If any modifications are required, please let me know. Thank you.

### CODE REVIEW

**Review by neila — CHANGES_REQUESTED** [review]
@wufengtao1 Great! Few things:

1. The source code beneath `docs/Polygon-Whitelist-NFT[ChainIDE]/en/resource/{code|Metadata_img|Metadata_json}/*` should be moved outside of this repository to [this repo](https://github.com/unchain-tech/Polygon-Whitelist-NFT) instead.

2. The files under `docs/Polygon-Whitelist-NFT[ChainIDE]/en/resource/Images/*` also need to be moved under `public/Polygon-Whitelist-NFT[ChainIDE]/images/*`. These formatting requirements are so that these documents can be seamlessly delivered through [our portal](https://app.unchain.tech/learn/).

3. The textlint is supposed to only run for Japanese grammar, but is misbehaving because this is our first exception so far. Do don't worry about that, I will fix this.

**Comment by neila** [comment]
Btw, I changed the base branch from `main` because I wanted to first deal with the formatting-related stuff in this PR, and then go over the document contents as necessary in the `add-chainide` branch before finally merging to main. cc @yk-saito

**Comment by wufengtao1** [comment]
@neila Received your feedback and I will complete the changes tomorrow as per your comments, thanks!

**Comment by wufengtao1** [comment]
@neila Hi, I have modified it, please check :)

**Review by neila — APPROVED** [review]
LGTM!

**Pull request merged**
